// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { HealthCheckApiV1HealthGetData, HealthCheckApiV1HealthGetResponse, ListJobsApiV1JobsGetData, ListJobsApiV1JobsGetResponse, ListJobsApiV1JobsGetError, CreateJobApiV1JobsPostData, CreateJobApiV1JobsPostResponse, CreateJobApiV1JobsPostError, DashboardStatsApiV1JobsDashboardStatsGetData, DashboardStatsApiV1JobsDashboardStatsGetResponse, GetJobApiV1JobsJobIdGetData, GetJobApiV1JobsJobIdGetResponse, GetJobApiV1JobsJobIdGetError, CancelJobApiV1JobsJobIdCancelPatchData, CancelJobApiV1JobsJobIdCancelPatchResponse, CancelJobApiV1JobsJobIdCancelPatchError, GetJobLogsApiV1JobsJobIdLogsGetData, GetJobLogsApiV1JobsJobIdLogsGetResponse, GetJobLogsApiV1JobsJobIdLogsGetError, ListDlqJobsApiV1DlqGetData, ListDlqJobsApiV1DlqGetResponse, RetryDlqJobApiV1DlqJobIdRetryPostData, RetryDlqJobApiV1DlqJobIdRetryPostResponse, RetryDlqJobApiV1DlqJobIdRetryPostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 * Return connectivity status for PostgreSQL and Redis.
 */
export const healthCheckApiV1HealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckApiV1HealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthCheckApiV1HealthGetResponse, unknown, ThrowOnError>({
        url: '/api/v1/health',
        ...options
    });
};

/**
 * List jobs
 * List jobs with optional filtering and pagination.
 */
export const listJobsApiV1JobsGet = <ThrowOnError extends boolean = false>(options?: Options<ListJobsApiV1JobsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListJobsApiV1JobsGetResponse, ListJobsApiV1JobsGetError, ThrowOnError>({
        url: '/api/v1/jobs',
        ...options
    });
};

/**
 * Create a job
 * Create a new job with optional DAG dependencies.
 *
 * If ``dependency_ids`` are provided, the job will not execute until all
 * parent jobs have completed. Circular dependencies are rejected.
 */
export const createJobApiV1JobsPost = <ThrowOnError extends boolean = false>(options: Options<CreateJobApiV1JobsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateJobApiV1JobsPostResponse, CreateJobApiV1JobsPostError, ThrowOnError>({
        url: '/api/v1/jobs',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Dashboard stats
 * Return job counts grouped by status for the dashboard view.
 */
export const dashboardStatsApiV1JobsDashboardStatsGet = <ThrowOnError extends boolean = false>(options?: Options<DashboardStatsApiV1JobsDashboardStatsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<DashboardStatsApiV1JobsDashboardStatsGetResponse, unknown, ThrowOnError>({
        url: '/api/v1/jobs/dashboard/stats',
        ...options
    });
};

/**
 * Get job details
 * Get a single job by ID.
 */
export const getJobApiV1JobsJobIdGet = <ThrowOnError extends boolean = false>(options: Options<GetJobApiV1JobsJobIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetJobApiV1JobsJobIdGetResponse, GetJobApiV1JobsJobIdGetError, ThrowOnError>({
        url: '/api/v1/jobs/{job_id}',
        ...options
    });
};

/**
 * Cancel a job
 * Cancel a pending or processing job.
 *
 * If the job is currently processing, a cooperative cancellation signal
 * is broadcast via Redis Pub/Sub to the worker.
 */
export const cancelJobApiV1JobsJobIdCancelPatch = <ThrowOnError extends boolean = false>(options: Options<CancelJobApiV1JobsJobIdCancelPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<CancelJobApiV1JobsJobIdCancelPatchResponse, CancelJobApiV1JobsJobIdCancelPatchError, ThrowOnError>({
        url: '/api/v1/jobs/{job_id}/cancel',
        ...options
    });
};

/**
 * Get job execution logs
 * Get structured execution logs for a specific job.
 */
export const getJobLogsApiV1JobsJobIdLogsGet = <ThrowOnError extends boolean = false>(options: Options<GetJobLogsApiV1JobsJobIdLogsGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetJobLogsApiV1JobsJobIdLogsGetResponse, GetJobLogsApiV1JobsJobIdLogsGetError, ThrowOnError>({
        url: '/api/v1/jobs/{job_id}/logs',
        ...options
    });
};

/**
 * List DLQ jobs
 * List all jobs that have exhausted their retries (dead-letter queue).
 *
 * These are jobs with ``status='failed'`` and ``retry_count >= max_retries``.
 * Includes ``error_details`` for inspection.
 */
export const listDlqJobsApiV1DlqGet = <ThrowOnError extends boolean = false>(options?: Options<ListDlqJobsApiV1DlqGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListDlqJobsApiV1DlqGetResponse, unknown, ThrowOnError>({
        url: '/api/v1/dlq',
        ...options
    });
};

/**
 * Retry a DLQ job
 * Manually retry a job from the dead-letter queue.
 *
 * Resets ``retry_count`` to 0, ``status`` to ``pending``, and clears
 * ``error_details``. The job re-enters the scheduler. If it fails again
 * after exhausting retries, it returns to the DLQ.
 */
export const retryDlqJobApiV1DlqJobIdRetryPost = <ThrowOnError extends boolean = false>(options: Options<RetryDlqJobApiV1DlqJobIdRetryPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RetryDlqJobApiV1DlqJobIdRetryPostResponse, RetryDlqJobApiV1DlqJobIdRetryPostError, ThrowOnError>({
        url: '/api/v1/dlq/{job_id}/retry',
        ...options
    });
};
