// This file is auto-generated by @hey-api/openapi-ts

/**
 * Job counts grouped by status — for the dashboard view.
 */
export type DashboardStats = {
    pending?: number;
    processing?: number;
    completed?: number;
    failed?: number;
    cancelled?: number;
    total?: number;
};

/**
 * All possible job lifecycle event types stored in execution logs.
 */
export type EventType = 'JOB_CREATED' | 'JOB_STARTED' | 'RETRY_ATTEMPTED' | 'JOB_FAILED' | 'JOB_CANCELLED' | 'JOB_COMPLETED' | 'JOB_RETRIED_FROM_DLQ' | 'RECURRING_SCHEDULED';

/**
 * Structured log entry returned by the API.
 */
export type ExecutionLogResponse = {
    id: number;
    job_id: string;
    event_type: EventType;
    log_data: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Schema for creating a new job.
 */
export type JobCreate = {
    type: string;
    /**
     * 1 = High, 2 = Medium, 3 = Low
     */
    priority?: JobPriority;
    payload?: {
        [key: string]: unknown;
    };
    /**
     * When to run. Defaults to now if omitted.
     */
    scheduled_at?: string | null;
    /**
     * Recurring interval. None = one-shot job.
     */
    interval?: JobInterval | null;
    /**
     * List of parent job IDs that must complete before this job runs.
     */
    dependency_ids?: Array<string>;
};

/**
 * Supported recurring intervals.
 */
export type JobInterval = 'every_1_minute' | 'every_5_minutes' | 'every_1_hour';

/**
 * Paginated list of jobs.
 */
export type JobListResponse = {
    jobs: Array<JobResponse>;
    total: number;
    offset: number;
    limit: number;
};

/**
 * Priority levels: lower number = higher priority.
 */
export type JobPriority = 1 | 2 | 3;

/**
 * Full job representation returned by the API.
 */
export type JobResponse = {
    id: string;
    type: string;
    priority: number;
    status: string;
    payload: {
        [key: string]: unknown;
    };
    error_details?: {
        [key: string]: unknown;
    } | null;
    retry_count: number;
    max_retries: number;
    scheduled_at: string;
    interval?: string | null;
    created_at: string;
    updated_at: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckApiV1HealthGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckApiV1HealthGetResponse = HealthCheckApiV1HealthGetResponses[keyof HealthCheckApiV1HealthGetResponses];

export type ListJobsApiV1JobsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status
         */
        status?: string | null;
        /**
         * Filter by job type
         */
        type?: string | null;
        /**
         * Filter by priority (1, 2, 3)
         */
        priority?: number | null;
        offset?: number;
        limit?: number;
    };
    url: '/api/v1/jobs';
};

export type ListJobsApiV1JobsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListJobsApiV1JobsGetError = ListJobsApiV1JobsGetErrors[keyof ListJobsApiV1JobsGetErrors];

export type ListJobsApiV1JobsGetResponses = {
    /**
     * Successful Response
     */
    200: JobListResponse;
};

export type ListJobsApiV1JobsGetResponse = ListJobsApiV1JobsGetResponses[keyof ListJobsApiV1JobsGetResponses];

export type CreateJobApiV1JobsPostData = {
    body: JobCreate;
    path?: never;
    query?: never;
    url: '/api/v1/jobs';
};

export type CreateJobApiV1JobsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateJobApiV1JobsPostError = CreateJobApiV1JobsPostErrors[keyof CreateJobApiV1JobsPostErrors];

export type CreateJobApiV1JobsPostResponses = {
    /**
     * Successful Response
     */
    201: JobResponse;
};

export type CreateJobApiV1JobsPostResponse = CreateJobApiV1JobsPostResponses[keyof CreateJobApiV1JobsPostResponses];

export type DashboardStatsApiV1JobsDashboardStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/jobs/dashboard/stats';
};

export type DashboardStatsApiV1JobsDashboardStatsGetResponses = {
    /**
     * Successful Response
     */
    200: DashboardStats;
};

export type DashboardStatsApiV1JobsDashboardStatsGetResponse = DashboardStatsApiV1JobsDashboardStatsGetResponses[keyof DashboardStatsApiV1JobsDashboardStatsGetResponses];

export type GetJobApiV1JobsJobIdGetData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}';
};

export type GetJobApiV1JobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobApiV1JobsJobIdGetError = GetJobApiV1JobsJobIdGetErrors[keyof GetJobApiV1JobsJobIdGetErrors];

export type GetJobApiV1JobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type GetJobApiV1JobsJobIdGetResponse = GetJobApiV1JobsJobIdGetResponses[keyof GetJobApiV1JobsJobIdGetResponses];

export type CancelJobApiV1JobsJobIdCancelPatchData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}/cancel';
};

export type CancelJobApiV1JobsJobIdCancelPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelJobApiV1JobsJobIdCancelPatchError = CancelJobApiV1JobsJobIdCancelPatchErrors[keyof CancelJobApiV1JobsJobIdCancelPatchErrors];

export type CancelJobApiV1JobsJobIdCancelPatchResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type CancelJobApiV1JobsJobIdCancelPatchResponse = CancelJobApiV1JobsJobIdCancelPatchResponses[keyof CancelJobApiV1JobsJobIdCancelPatchResponses];

export type GetJobLogsApiV1JobsJobIdLogsGetData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}/logs';
};

export type GetJobLogsApiV1JobsJobIdLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobLogsApiV1JobsJobIdLogsGetError = GetJobLogsApiV1JobsJobIdLogsGetErrors[keyof GetJobLogsApiV1JobsJobIdLogsGetErrors];

export type GetJobLogsApiV1JobsJobIdLogsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ExecutionLogResponse>;
};

export type GetJobLogsApiV1JobsJobIdLogsGetResponse = GetJobLogsApiV1JobsJobIdLogsGetResponses[keyof GetJobLogsApiV1JobsJobIdLogsGetResponses];

export type ListDlqJobsApiV1DlqGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dlq';
};

export type ListDlqJobsApiV1DlqGetResponses = {
    /**
     * Successful Response
     */
    200: Array<JobResponse>;
};

export type ListDlqJobsApiV1DlqGetResponse = ListDlqJobsApiV1DlqGetResponses[keyof ListDlqJobsApiV1DlqGetResponses];

export type RetryDlqJobApiV1DlqJobIdRetryPostData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/api/v1/dlq/{job_id}/retry';
};

export type RetryDlqJobApiV1DlqJobIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryDlqJobApiV1DlqJobIdRetryPostError = RetryDlqJobApiV1DlqJobIdRetryPostErrors[keyof RetryDlqJobApiV1DlqJobIdRetryPostErrors];

export type RetryDlqJobApiV1DlqJobIdRetryPostResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type RetryDlqJobApiV1DlqJobIdRetryPostResponse = RetryDlqJobApiV1DlqJobIdRetryPostResponses[keyof RetryDlqJobApiV1DlqJobIdRetryPostResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
